version: '3'
services:
  resume:
    build:
      context: .
      dockerfile: Dockerfile
    image: resume
    container_name: resume
    restart: always
    expose:
      - 80
    volumes:
      - ./:/usr/share/nginx/html/
    networks:
      - nginx

networks:
  nginx:
    external: true
