FROM node:22-alpine AS builder
LABEL maintainer="Shenna Risqianto Wilfred Piri <shennawew@outlook.com>"

WORKDIR /app
COPY package*.json ./
RUN npm ci --ignore-scripts
COPY . .
RUN npm run build

FROM lipanski/docker-static-website:2.4.0
USER static
WORKDIR /home/static
COPY --from=builder /app/dist .
COPY --from=builder /app/src/assets/favicon.ico ./favicon.ico
CMD ["/busybox-httpd", "-f", "-v", "-p", "80", "-c", "httpd.conf"]
