FROM node:22-alpine AS builder
LABEL maintainer="Shenna Risqianto Wilfred Piri <shenna@rwpiri.com>" \
      org.opencontainers.image.authors="Shenna Risqianto Wilfred Piri <shenna@rwpiri.com>" \
      org.opencontainers.image.url="https://github.com/shennarwp/resume2" \
      org.opencontainers.image.title="resume" \
      org.opencontainers.image.description="Shenna RWP's résumé source code, developed further based on this. \
        Live version can be seen on https://shenna.rwpiri.com"

WORKDIR /app
COPY package*.json ./
RUN npm ci --ignore-scripts
COPY . .
RUN npm run build

FROM nginx:1.27-alpine-slim
# SvelteKit with adapter-static outputs to 'build' by default
COPY --from=builder /app/build /usr/share/nginx/html/
# Port 80 is the default for nginx
EXPOSE 80
