services:
  resume:
    image: ghcr.io/shennarwp/resume:nginx-latest
    container_name: resume
    restart: always
    expose:
      - 8080
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider --quiet http://127.0.0.1:8080/ || exit 1']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - nginx

networks:
  nginx:
    external: true
