version: "3"
services:
  resume:
    image: shennarwp/resume
    container_name: resume
    restart: always
    expose:
      - 8080
    networks:
      - nginx

networks:
  nginx:
    external: true
