FROM node:24.18.1-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci --ignore-scripts --no-audit --no-fund
COPY . .
RUN npm run build

FROM lipanski/docker-static-website:2.6.0
LABEL maintainer="Shenna Risqianto Wilfred Piri <shenna@rwpiri.com>"
LABEL org.opencontainers.image.authors="Shenna Risqianto Wilfred Piri <shenna@rwpiri.com>"
LABEL org.opencontainers.image.url="https://github.com/shennarwp/resume2"
LABEL org.opencontainers.image.title="resume"
LABEL org.opencontainers.image.description="Shenna RWP's résumé source code. \
        Live version can be seen on https://shenna.rwpiri.com"

USER static
WORKDIR /home/static
# SvelteKit with adapter-static defaults to 'build' folder
COPY --from=builder /app/build .
CMD ["/busybox-httpd", "-f", "-v", "-p", "80", "-c", "httpd.conf"]
