FROM node:22-alpine AS builder
LABEL maintainer="Shenna Risqianto Wilfred Piri <shennawew@outlook.com>"

WORKDIR /app
COPY package*.json ./
RUN npm ci --ignore-scripts
COPY . .
RUN npm run build

FROM nginx:1.27-alpine-slim
COPY --from=builder /app/dist /usr/share/nginx/html/