sonar.organization=shennarwp
sonar.projectKey=shennarwp_resume2
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.exclusions=**/*.test.ts,**/*.spec.ts,azure-template/**
sonar.coverage.exclusions=**/*.test.ts,src/setupTest.ts