name: Renovate

on:
  schedule:
    - cron: '30 1 * * *' # Runs daily at 01:30
  push:
    branches: [add-renovate]
  workflow_dispatch: # Allows manual triggering

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Renovate
        uses: renovatebot/github-action@02f4fdeb479bbb229caa7ad82cb5e691c07e80b3 # v41.0.14
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_PLATFORM_COMMIT: "true"
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.WORKFLOW_TOKEN }}